In [8]:
import os

if os.path.exists(r'data\new_career_dataset.csv'):
    print('exist')

exist


In [10]:
from dataclasses import dataclass
import pandas as pd

@dataclass
class DataPath:
    data_path: str = r'data\new_career_dataset.csv'
    artifact_data_path = r'artifacts/data.csv'

paths = DataPath()

df = pd.read_csv(paths.data_path)
df.head()

Interest   Skill_Level Work_Style  Education Personality Problem_Solving  \
0         art        expert   flexible    masters     thinker        creative   
1  technology      advanced   flexible        phd     thinker         logical   
2         art  intermediate       team        phd   extrovert       intuitive   
3    business        expert     remote    diploma   extrovert       intuitive   
4  technology        expert       solo  bachelors     thinker        creative   

        Tech Communication     Leadership Creativity  \
0  very high     excellent         strong     medium   
1       high          poor       moderate  very high   
2       high     excellent  collaborative        low   
3       high        fluent  collaborative       high   
4  very high     excellent      visionary     medium   

                          Career  
0               business analyst  
1      site reliability engineer  
2              financial analyst  
3  speech recognition specialist  
4                 game developer

In [11]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [12]:
X = df.drop(['Career'], axis=1)
y = df['Career']

In [13]:
columns = X.columns

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
preprocessor = ColumnTransformer([
    ('OHE', OneHotEncoder(sparse_output=False), columns)
], remainder='passthrough')

In [16]:
X_train_trf = preprocessor.fit_transform(X_train)
X_test_trf = preprocessor.transform(X_test)

In [17]:
le = LabelEncoder()

y_train_trf = le.fit_transform(y_train)
y_test_trf = le.transform(y_test)

In [18]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=0.2)

In [19]:
test.shape

(1000, 11)

In [20]:
df

Interest   Skill_Level Work_Style    Education Personality  \
0            art        expert   flexible      masters     thinker   
1     technology      advanced   flexible          phd     thinker   
2            art  intermediate       team          phd   extrovert   
3       business        expert     remote      diploma   extrovert   
4     technology        expert       solo    bachelors     thinker   
...          ...           ...        ...          ...         ...   
4995  technology      advanced       solo    bachelors     thinker   
4996     science  intermediate   flexible  high school   extrovert   
4997         art      advanced   flexible      diploma   introvert   
4998    medicine  intermediate       team      masters        doer   
4999    medicine      advanced   flexible      diploma   extrovert   

     Problem_Solving       Tech Communication     Leadership   Creativity  \
0           creative  very high     excellent         strong       medium   
1            logical       high          poor       moderate    very high   
2          intuitive       high     excellent  collaborative          low   
3          intuitive       high        fluent  collaborative         high   
4           creative  very high     excellent      visionary       medium   
...              ...        ...           ...            ...          ...   
4995       intuitive  very high        fluent  collaborative          low   
4996         logical     medium          poor  collaborative       medium   
4997       intuitive  very high          poor      visionary         high   
4998        creative  very high          poor       moderate         high   
4999      analytical       high   outstanding      visionary  exceptional   

                             Career  
0                  business analyst  
1         site reliability engineer  
2                 financial analyst  
3     speech recognition specialist  
4                    game developer  
...                             ...  
4995                  web developer  
4996            automation engineer  
4997               technical writer  
4998                 iot specialist  
4999       computer vision engineer  

[5000 rows x 11 columns]

In [21]:
X_train_trf, X_test_trf, y_train_trf, y_test_trf

(array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 1.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 1.],
        [0., 1., 0., ..., 0., 0., 1.],
        [1., 0., 0., ..., 0., 0., 1.],
        ...,
        [1., 0., 0., ..., 0., 0., 1.],
        [0., 0., 1., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.]]),
 array([20, 16,  0, ..., 15, 37, 12]),
 array([39, 22, 18, 20, 14, 14,  6,  0, 10, 33, 26, 35, 35, 18, 19, 39, 32,
        31,  4, 34, 20, 36,  7, 19, 39, 10,  0, 23,  5,  3, 14, 34, 18, 33,
        13, 31, 36, 12,  0, 25, 33, 12,  0, 28, 34, 35, 28, 34,  5, 34, 16,
        36, 29, 33, 14, 26, 29, 38, 14, 12,  6, 39,  8, 26,  6, 24, 14, 22,
        26, 36,  4, 31, 22, 25, 24, 11, 34, 32, 15, 17,  0, 10,  3, 21, 23,
        31, 33, 37, 32,  3,  7,  0, 31,  7,  3, 14, 34, 17, 26, 30,  5,  7,
       

In [23]:
import numpy as np

len(np.unique(y_train_trf))

40

In [90]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2

In [61]:
len(le.classes_)

40

In [91]:
model = Sequential()
model.add(Dense(256, activation='relu', input_shape=(X_train_trf.shape[1],), kernel_regularizer=l2(0.01)))
# model.add(Dropout(0.2))
model.add(Dense(128, activation='relu', kernel_regularizer=l2(0.01)))
model.add(Dense(64, activation='relu', kernel_regularizer=l2(0.01)))
# model.add(Dropout(0.2))
model.add(Dense(40, activation='softmax'))

In [92]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_23 (Dense)                │ (None, 256)            │        12,288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_26 (Dense)                │ (None, 40)             │         2,600 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 56,040 (218.91 KB)

 Trainable params: 56,040 (218.91 KB)

 Non-trainable params: 0 (0.00 B)

In [93]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [94]:
model.fit(
    X_train_trf, 
    y_train_trf,
    validation_data=(X_test_trf, y_test_trf),
    epochs=20
)

Epoch 1/20


125/125 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0251 - loss: 5.8726 - val_accuracy: 0.0260 - val_loss: 3.9884
Epoch 2/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0267 - loss: 3.8611 - val_accuracy: 0.0300 - val_loss: 3.7053
Epoch 3/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0289 - loss: 3.6972 - val_accuracy: 0.0300 - val_loss: 3.6904
Epoch 4/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0288 - loss: 3.6876 - val_accuracy: 0.0300 - val_loss: 3.6899
Epoch 5/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0363 - loss: 3.6866 - val_accuracy: 0.0300 - val_loss: 3.6904
Epoch 6/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0292 - loss: 3.6868 - val_accuracy: 0.0300 - val_loss: 3.6908
Epoch 7/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0292 - loss: 3.6872 - val_accuracy: 0.0300 - val_loss: 3.6911
Epoch 8/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0299 - loss: 3.6865 - val_accuracy: 0.0230 - val_

In [98]:
X_test

Interest   Skill_Level Work_Style    Education Personality  \
2891    medicine        expert     office      masters        doer   
493     business      advanced       team  high school        doer   
670      science      beginner     office  high school      leader   
3610  technology      advanced     remote          phd     thinker   
4773    medicine      beginner       solo          phd   extrovert   
...          ...           ...        ...          ...         ...   
1129         art      beginner       solo  high school      leader   
2894     science      advanced       solo      diploma   introvert   
138     business  intermediate       solo      diploma      leader   
592     medicine        expert       team    bachelors     thinker   
3517         art      beginner       team    bachelors   introvert   

     Problem_Solving    Tech Communication     Leadership   Creativity  
2891         logical     low          poor  collaborative          low  
493         creative  medium        fluent  collaborative         high  
670         creative  medium          poor       moderate          low  
3610       practical    high   outstanding      visionary  exceptional  
4773         logical     low          poor  collaborative          low  
...              ...     ...           ...            ...          ...  
1129         logical    high   outstanding      visionary    very high  
2894        creative     low          poor  collaborative          low  
138        practical  medium        fluent         strong  exceptional  
592       analytical  medium     excellent  collaborative  exceptional  
3517         logical  medium          poor         strong       medium  

[1000 rows x 10 columns]

In [156]:
input_qurie = list(X_test.loc[2894])

In [157]:
import numpy as np

input_qurie = pd.DataFrame(np.array([input_qurie]), columns=columns)

In [158]:
input_qurie

Interest Skill_Level Work_Style Education Personality Problem_Solving Tech  \
0  science    advanced       solo   diploma   introvert        creative  low   

  Communication     Leadership Creativity  
0          poor  collaborative        low

In [159]:
prediction_input = np.array([preprocessor.transform(input_qurie)[0]])

In [160]:
prediction_input

array([[0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [161]:
prediction = model.predict(prediction_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


In [162]:
prediction

array([[0.02396186, 0.02263361, 0.0234366 , 0.0231523 , 0.02599659,
        0.02623536, 0.02284913, 0.02545882, 0.02301746, 0.02569979,
        0.02785396, 0.02876105, 0.02372194, 0.02597085, 0.02383758,
        0.0267227 , 0.0255262 , 0.02420458, 0.02856317, 0.0243386 ,
        0.02598333, 0.02588741, 0.02683465, 0.02321241, 0.02278556,
        0.02470937, 0.0265565 , 0.02340666, 0.02365896, 0.02555453,
        0.0216676 , 0.02251566, 0.02678259, 0.02429385, 0.0263499 ,
        0.02456799, 0.02657984, 0.0277435 , 0.02301442, 0.02595302]],
      dtype=float32)

In [163]:
np.argmax(prediction, axis=1)[0]

11

In [164]:
le.classes_[np.argmax(prediction, axis=1)[0]]

'data analyst'

In [6]:
# Importing Necessary Dependencies
import os
import sys

import pandas as pd
import numpy as np

from dataclasses import dataclass

from src.utils.exception import CustomException
from src.utils.logger import get_logger

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

# creating our logger object
logger = get_logger('Data_Preprocessing')

# Creating our data class for paths
@dataclass
class DataPaths:
    training_data_path: str = 'artifacts/train.csv'
    testing_data_path: str = 'artifacts/test.csv'

# Creating our main data preprocessing class
class DataPreprocessing:
    def __init__(self):
        self.data_paths = DataPaths()

        self.DEPENDENT_FEATURE = "Career"

    def data_splitter(self, data):
        '''
        This method will take data and convert it into training and testing data and stores it in artifacts folder.

        Parameters:
            data: Dataframe.

        Returns:
            train and test data paths
        '''

        try:
            # Splitting our data into train and test part 80/20
            logger.info('Splitting data into 80/20 part')

            train_data, test_data = train_test_split(data, test_size=0.2)

            logger.info('Data Splitted')
            logger.info('Saving train and test data to artifacts')

            #saving train and test data to artifact
            logger.info('Saving train data to artifact')
            train_data.to_csv(self.data_paths.training_data_path, index=False)

            logger.info('Saving test data to artifacts')
            test_data.to_csv(self.data_paths.testing_data_path, index=False)

            logger.info('train and test data saving done')

            # returning training and testing data paths
            return (
                self.data_paths.training_data_path,
                self.data_paths.testing_data_path
            )
        
        except Exception as e:
            logger.error(e)
            CustomException(e, sys)

    def training_testing_splitter(self, data):
        '''
        This method will take data and returns X_train, X_test, y_train, y_test

        Parameters:
            data: DataFrame
        
        Returns:
            X_train, X_test, y_train, y_test
        '''

        try:
            # Sending data to split it into train and testing part.
            logger.info('Splitting it into training and testing part')

            train_path, test_path = self.data_splitter(data=data)

            logger.info('Loading train and test data path')

            logger.info('Loading training data path')
            train_data = pd.read_csv(train_path)

            logger.info('Loading testing data path')
            test_data = pd.read_csv(test_path)

            logger.info('Train and Test data loaded')

            # Splitting data into Independent and Dependent features

            logger.info("Splitting training data to dependent and independt feature")
            X_train, y_train = train_data.drop([self.DEPENDENT_FEATURE], axis=1), train_data[self.DEPENDENT_FEATURE]

            logger.info('Splitting testing data into dependent and independent feature')
            X_test, y_test = test_data.drop([self.DEPENDENT_FEATURE], axis=1), test_data[self.DEPENDENT_FEATURE]

            logger.info('Data Splitting Completed')
            
            # Returning X_train, X_test, y_train, y_test
            return (
                X_train, 
                X_test,
                y_train,
                y_test
            )

        except Exception as e:
            logger.error(e)
            CustomException(e, sys)

    def get_preprocessors(self, X_train, y_train):
        '''
        This method creates X_preprocessor and y_preprocessor and returns it

        Parameters:
            columns: for creating X_preprocessor columns is required for preprocessor.

        Returns:
            X_preprocessor, y_preprocessor.
        '''

        try:
            # Creating our preprocessor object
            logger.info('Creating our preprocessors object')

            logger.info("Creating our X_preprocessor")

            X_preprocessors = {
                col: LabelEncoder().fit(X_train[col]) for col in X_train.columns
            }

            logger.info('Creating our y_preprocessor')
            y_preprocessor = LabelEncoder().fit(y_train)

            logger.info('Preprocessor Object Created')

            # Returning the preprocessor objects
            return (
                X_preprocessors,
                y_preprocessor
            )

        except Exception as e:
            logger.error(e)
            CustomException(e, sys)

    def initiate_Preprocessing(self, data_path):
        '''
        This main method will take data path, splits it, preprocessed it and returns it.

        Parameters:
            data_path: our data path.

        Returns:
            X_train, X_test, y_train, y_test.
        '''

        try:
            # Starting our data preprocessing
            logger.info('Data Preprocessing Initialized')

            if os.path.exists(data_path):
                # reading our data from path
                logger.info("Reading our data")
                data = pd.read_csv(data_path)
                logger.info('Data Loaded')

                # Getting X_train, X_test, y_train, y_test
                X_train, X_test, y_train, y_test = self.training_testing_splitter(data=data)

                # Getting our preprocessor objects
                logger.info('Entering get_preprocessor method')
                X_preprocessors, y_preprocessor = self.get_preprocessors(X_train=X_train, y_train=y_train)

                # Initiating preprocessing on our data
                logger.info("Starts preprocessing")

                logger.info("Preprocessing on Independent Data")

                # Encode X_train
                X_train_trf = np.column_stack([
                    X_preprocessors[col].transform(X_train[col]) for col in X_train.columns
                ])

                # Encode X_test
                X_test_trf = np.column_stack([
                    X_preprocessors[col].transform(X_test[col]) for col in X_test.columns
                ])

                logger.info("Preprocessing on Dependent Features")

                # transforming on y_train
                y_train_trf = y_preprocessor.transform(y_train)

                # Transforming on y_test
                y_test_trf = y_preprocessor.transform(y_test)

                logger.info("All Preprocessing Completed")

                # Returning Transformed and model ready to train data
                return (
                    X_train_trf,
                    X_test_trf,
                    y_train_trf,
                    y_test_trf
                )
            
            else:
                logger.error('Data Not exists')

        except Exception as e:
            logger.error(e)
            CustomException(e, sys)


# For testing purpose
if __name__ == '__main__':
    from src.components.data_ingestion import DataIngestion

    data_ingestion = DataIngestion()

    data_path = data_ingestion.load_data()

    data_preprocessing = DataPreprocessing()

    X_train, X_test, y_train, y_test = data_preprocessing.initiate_Preprocessing(data_path=data_path)

    print(X_train)

In [7]:
obj = DataPreprocessing()
obj.temp()

AttributeError: 'DataPreprocessing' object has no attribute 'label_encoders'