In [1]:
import os

if os.path.exists(r'data\new_career_dataset.csv'):
    print('exist')

exist


In [2]:
from dataclasses import dataclass
import pandas as pd

@dataclass
class DataPath:
    data_path: str = r'data\new_career_dataset.csv'
    artifact_data_path = r'artifacts/data.csv'

paths = DataPath()

df = pd.read_csv(paths.data_path)
df.head()

Interest   Skill_Level Work_Style  Education Personality Problem_Solving  \
0         art        expert   flexible    masters     thinker        creative   
1  technology      advanced   flexible        phd     thinker         logical   
2         art  intermediate       team        phd   extrovert       intuitive   
3    business        expert     remote    diploma   extrovert       intuitive   
4  technology        expert       solo  bachelors     thinker        creative   

        Tech Communication     Leadership Creativity  \
0  very high     excellent         strong     medium   
1       high          poor       moderate  very high   
2       high     excellent  collaborative        low   
3       high        fluent  collaborative       high   
4  very high     excellent      visionary     medium   

                          Career  
0               business analyst  
1      site reliability engineer  
2              financial analyst  
3  speech recognition specialist  
4                 game developer

In [3]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [4]:
X = df.drop(['Career'], axis=1)
y = df['Career']

In [5]:
columns = X.columns

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
preprocessor = ColumnTransformer([
    ('OHE', OneHotEncoder(sparse_output=False), columns)
], remainder='passthrough')

In [8]:
X_train_trf = preprocessor.fit_transform(X_train)
X_test_trf = preprocessor.transform(X_test)

In [9]:
le = LabelEncoder()

y_train_trf = le.fit_transform(y_train)
y_test_trf = le.transform(y_test)

In [10]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=0.2)

In [11]:
test.shape

(1000, 11)

In [12]:
df

Interest   Skill_Level Work_Style    Education Personality  \
0            art        expert   flexible      masters     thinker   
1     technology      advanced   flexible          phd     thinker   
2            art  intermediate       team          phd   extrovert   
3       business        expert     remote      diploma   extrovert   
4     technology        expert       solo    bachelors     thinker   
...          ...           ...        ...          ...         ...   
4995  technology      advanced       solo    bachelors     thinker   
4996     science  intermediate   flexible  high school   extrovert   
4997         art      advanced   flexible      diploma   introvert   
4998    medicine  intermediate       team      masters        doer   
4999    medicine      advanced   flexible      diploma   extrovert   

     Problem_Solving       Tech Communication     Leadership   Creativity  \
0           creative  very high     excellent         strong       medium   
1            logical       high          poor       moderate    very high   
2          intuitive       high     excellent  collaborative          low   
3          intuitive       high        fluent  collaborative         high   
4           creative  very high     excellent      visionary       medium   
...              ...        ...           ...            ...          ...   
4995       intuitive  very high        fluent  collaborative          low   
4996         logical     medium          poor  collaborative       medium   
4997       intuitive  very high          poor      visionary         high   
4998        creative  very high          poor       moderate         high   
4999      analytical       high   outstanding      visionary  exceptional   

                             Career  
0                  business analyst  
1         site reliability engineer  
2                 financial analyst  
3     speech recognition specialist  
4                    game developer  
...                             ...  
4995                  web developer  
4996            automation engineer  
4997               technical writer  
4998                 iot specialist  
4999       computer vision engineer  

[5000 rows x 11 columns]

In [13]:
X_train_trf, X_test_trf, y_train_trf, y_test_trf

(array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 1., 0.],
        [1., 0., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        ...,
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 1., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]]),
 array([23, 29, 13, ...,  6, 11, 38]),
 array([ 5, 20, 26, 13, 28, 35, 16, 15, 14, 13, 23,  8, 31, 33,  0, 14, 21,
        26, 35, 24, 12, 10, 14, 25,  1,  8, 34,  6, 13, 39, 30, 26, 18, 25,
        21, 38,  7, 28,  8,  9, 30, 24, 18,  9, 28, 36, 16, 15, 33,  7,  9,
        20,  1, 30, 33, 15, 11, 18, 20, 12, 12,  4, 25, 23, 19, 20, 25, 25,
        21,  0, 32, 14,  4, 33, 27, 35, 20, 24, 10, 31, 39,  9,  2,  4, 32,
        27,  2, 14, 23, 16, 28,  0, 12, 10, 18, 24,  2, 27,  0, 26, 39, 26,
       

In [14]:
import numpy as np

len(np.unique(y_train_trf))

40

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2

In [16]:
len(le.classes_)

40

In [17]:
model = Sequential()
model.add(Dense(256, activation='relu', input_shape=(X_train_trf.shape[1],), kernel_regularizer=l2(0.01)))
# model.add(Dropout(0.2))
model.add(Dense(128, activation='relu', kernel_regularizer=l2(0.01)))
model.add(Dense(64, activation='relu', kernel_regularizer=l2(0.01)))
# model.add(Dropout(0.2))
model.add(Dense(40, activation='softmax'))

c:\Users\TALHA PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 256)            │        12,288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 40)             │         2,600 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 56,040 (218.91 KB)

 Trainable params: 56,040 (218.91 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [20]:
model.fit(
    X_train_trf, 
    y_train_trf,
    validation_data=(X_test_trf, y_test_trf),
    epochs=20
)

Epoch 1/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0267 - loss: 5.8749 - val_accuracy: 0.0230 - val_loss: 3.9931
Epoch 2/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0352 - loss: 3.8641 - val_accuracy: 0.0200 - val_loss: 3.7083
Epoch 3/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0287 - loss: 3.6965 - val_accuracy: 0.0200 - val_loss: 3.6926
Epoch 4/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0289 - loss: 3.6864 - val_accuracy: 0.0200 - val_loss: 3.6923
Epoch 5/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0283 - loss: 3.6866 - val_accuracy: 0.0240 - val_loss: 3.6933
Epoch 6/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0248 - loss: 3.6876 - val_accuracy: 0.0200 - val_loss: 3.6939
Epoch 7/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0292 - loss: 3.6854 - val_accuracy: 0.0240 - val_loss: 3.6944
Epoch 8/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0323 - loss: 3.6860 - val_accuracy: 0.

In [21]:
X_test

Interest   Skill_Level Work_Style    Education Personality  \
3932     science      advanced       team      diploma        doer   
2247     science      beginner       solo  high school   extrovert   
636   technology        expert       team    bachelors   introvert   
3327    business      beginner     remote      masters     thinker   
4457    medicine  intermediate       solo  high school      leader   
...          ...           ...        ...          ...         ...   
3235    medicine      advanced     office          phd   introvert   
3409     science      beginner     office    bachelors     thinker   
226     medicine        expert     office          phd   introvert   
2568    business      beginner     remote  high school     thinker   
773          art      advanced     remote      masters     thinker   

     Problem_Solving       Tech Communication     Leadership   Creativity  
3932      analytical     medium   outstanding  collaborative       medium  
2247         logical     medium     excellent  collaborative         high  
636        intuitive     medium     excellent  collaborative          low  
3327       intuitive        low       average      visionary         high  
4457         logical       high   outstanding      visionary          low  
...              ...        ...           ...            ...          ...  
3235       practical       high   outstanding         strong         high  
3409       intuitive        low   outstanding  collaborative  exceptional  
226       analytical     medium          poor       moderate         high  
2568        creative        low   outstanding  collaborative          low  
773          logical  very high   outstanding  collaborative         high  

[1000 rows x 10 columns]

In [41]:
input_qurie = list(X_test.loc[3327])

In [42]:
import numpy as np

input_qurie = pd.DataFrame(np.array([input_qurie]), columns=columns)

In [43]:
input_qurie

Interest Skill_Level Work_Style Education Personality Problem_Solving Tech  \
0  business    beginner     remote   masters     thinker       intuitive  low   

  Communication Leadership Creativity  
0       average  visionary       high

In [44]:
prediction_input = np.array([preprocessor.transform(input_qurie)[0]])

In [45]:
prediction_input

array([[0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.]])

In [46]:
prediction = model.predict(prediction_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step


In [47]:
prediction

array([[0.02323509, 0.02246543, 0.02245258, 0.02570332, 0.02901984,
        0.02531909, 0.02451888, 0.02602521, 0.02340465, 0.02479806,
        0.02811375, 0.02636848, 0.02013308, 0.02698939, 0.02394156,
        0.02495179, 0.02590425, 0.02495153, 0.0273338 , 0.02424812,
        0.02554729, 0.02472056, 0.02797652, 0.02119412, 0.02197383,
        0.02465985, 0.02474964, 0.02340035, 0.02281495, 0.02572646,
        0.02262733, 0.02311587, 0.02850647, 0.02487605, 0.02884007,
        0.02326295, 0.02623469, 0.02620493, 0.02416678, 0.02952344]],
      dtype=float32)

In [48]:
np.argmax(prediction, axis=1)[0]

39

In [49]:
le.classes_[np.argmax(prediction, axis=1)[0]]

'web developer'

In [51]:
model.evaluate(X_test_trf, y_test_trf)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0221 - loss: 3.6985


[3.6964550018310547, 0.019999999552965164]

In [6]:
# Importing Necessary Dependencies
import os
import sys

import pandas as pd
import numpy as np

from dataclasses import dataclass

from src.utils.exception import CustomException
from src.utils.logger import get_logger

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

# creating our logger object
logger = get_logger('Data_Preprocessing')

# Creating our data class for paths
@dataclass
class DataPaths:
    training_data_path: str = 'artifacts/train.csv'
    testing_data_path: str = 'artifacts/test.csv'

# Creating our main data preprocessing class
class DataPreprocessing:
    def __init__(self):
        self.data_paths = DataPaths()

        self.DEPENDENT_FEATURE = "Career"

    def data_splitter(self, data):
        '''
        This method will take data and convert it into training and testing data and stores it in artifacts folder.

        Parameters:
            data: Dataframe.

        Returns:
            train and test data paths
        '''

        try:
            # Splitting our data into train and test part 80/20
            logger.info('Splitting data into 80/20 part')

            train_data, test_data = train_test_split(data, test_size=0.2)

            logger.info('Data Splitted')
            logger.info('Saving train and test data to artifacts')

            #saving train and test data to artifact
            logger.info('Saving train data to artifact')
            train_data.to_csv(self.data_paths.training_data_path, index=False)

            logger.info('Saving test data to artifacts')
            test_data.to_csv(self.data_paths.testing_data_path, index=False)

            logger.info('train and test data saving done')

            # returning training and testing data paths
            return (
                self.data_paths.training_data_path,
                self.data_paths.testing_data_path
            )
        
        except Exception as e:
            logger.error(e)
            CustomException(e, sys)

    def training_testing_splitter(self, data):
        '''
        This method will take data and returns X_train, X_test, y_train, y_test

        Parameters:
            data: DataFrame
        
        Returns:
            X_train, X_test, y_train, y_test
        '''

        try:
            # Sending data to split it into train and testing part.
            logger.info('Splitting it into training and testing part')

            train_path, test_path = self.data_splitter(data=data)

            logger.info('Loading train and test data path')

            logger.info('Loading training data path')
            train_data = pd.read_csv(train_path)

            logger.info('Loading testing data path')
            test_data = pd.read_csv(test_path)

            logger.info('Train and Test data loaded')

            # Splitting data into Independent and Dependent features

            logger.info("Splitting training data to dependent and independt feature")
            X_train, y_train = train_data.drop([self.DEPENDENT_FEATURE], axis=1), train_data[self.DEPENDENT_FEATURE]

            logger.info('Splitting testing data into dependent and independent feature')
            X_test, y_test = test_data.drop([self.DEPENDENT_FEATURE], axis=1), test_data[self.DEPENDENT_FEATURE]

            logger.info('Data Splitting Completed')
            
            # Returning X_train, X_test, y_train, y_test
            return (
                X_train, 
                X_test,
                y_train,
                y_test
            )

        except Exception as e:
            logger.error(e)
            CustomException(e, sys)

    def get_preprocessors(self, X_train, y_train):
        '''
        This method creates X_preprocessor and y_preprocessor and returns it

        Parameters:
            columns: for creating X_preprocessor columns is required for preprocessor.

        Returns:
            X_preprocessor, y_preprocessor.
        '''

        try:
            # Creating our preprocessor object
            logger.info('Creating our preprocessors object')

            logger.info("Creating our X_preprocessor")

            X_preprocessors = {
                col: LabelEncoder().fit(X_train[col]) for col in X_train.columns
            }

            logger.info('Creating our y_preprocessor')
            y_preprocessor = LabelEncoder().fit(y_train)

            logger.info('Preprocessor Object Created')

            # Returning the preprocessor objects
            return (
                X_preprocessors,
                y_preprocessor
            )

        except Exception as e:
            logger.error(e)
            CustomException(e, sys)

    def initiate_Preprocessing(self, data_path):
        '''
        This main method will take data path, splits it, preprocessed it and returns it.

        Parameters:
            data_path: our data path.

        Returns:
            X_train, X_test, y_train, y_test.
        '''

        try:
            # Starting our data preprocessing
            logger.info('Data Preprocessing Initialized')

            if os.path.exists(data_path):
                # reading our data from path
                logger.info("Reading our data")
                data = pd.read_csv(data_path)
                logger.info('Data Loaded')

                # Getting X_train, X_test, y_train, y_test
                X_train, X_test, y_train, y_test = self.training_testing_splitter(data=data)

                # Getting our preprocessor objects
                logger.info('Entering get_preprocessor method')
                X_preprocessors, y_preprocessor = self.get_preprocessors(X_train=X_train, y_train=y_train)

                # Initiating preprocessing on our data
                logger.info("Starts preprocessing")

                logger.info("Preprocessing on Independent Data")

                # Encode X_train
                X_train_trf = np.column_stack([
                    X_preprocessors[col].transform(X_train[col]) for col in X_train.columns
                ])

                # Encode X_test
                X_test_trf = np.column_stack([
                    X_preprocessors[col].transform(X_test[col]) for col in X_test.columns
                ])

                logger.info("Preprocessing on Dependent Features")

                # transforming on y_train
                y_train_trf = y_preprocessor.transform(y_train)

                # Transforming on y_test
                y_test_trf = y_preprocessor.transform(y_test)

                logger.info("All Preprocessing Completed")

                # Returning Transformed and model ready to train data
                return (
                    X_train_trf,
                    X_test_trf,
                    y_train_trf,
                    y_test_trf
                )
            
            else:
                logger.error('Data Not exists')

        except Exception as e:
            logger.error(e)
            CustomException(e, sys)


# For testing purpose
if __name__ == '__main__':
    from src.components.data_ingestion import DataIngestion

    data_ingestion = DataIngestion()

    data_path = data_ingestion.load_data()

    data_preprocessing = DataPreprocessing()

    X_train, X_test, y_train, y_test = data_preprocessing.initiate_Preprocessing(data_path=data_path)

    print(X_train)

In [7]:
obj = DataPreprocessing()
obj.temp()

AttributeError: 'DataPreprocessing' object has no attribute 'label_encoders'

In [52]:
X_train.head()

Interest   Skill_Level Work_Style    Education Personality  \
1373   science  intermediate   flexible      masters      leader   
724   medicine      beginner     office  high school   introvert   
4166   science        expert   flexible      diploma   extrovert   
3758  medicine      beginner       solo  high school      leader   
1014   science      advanced   flexible    bachelors   extrovert   

     Problem_Solving       Tech Communication     Leadership   Creativity  
1373       intuitive     medium          poor  collaborative       medium  
724         creative  very high          poor  collaborative         high  
4166       intuitive       high     excellent      visionary  exceptional  
3758      analytical       high     excellent      visionary          low  
1014      analytical       high   outstanding  collaborative         high

In [53]:
np.unique(y_train)

array(['ai ethics researcher', 'ai researcher', 'algorithm engineer',
       'augmented reality developer', 'automation engineer',
       'bioinformatics scientist', 'blockchain developer',
       'business analyst', 'cloud architect', 'computer vision engineer',
       'cybersecurity analyst', 'data analyst', 'data engineer',
       'data scientist', 'database administrator',
       'deep learning engineer', 'devops engineer',
       'embedded systems engineer', 'financial analyst',
       'full stack developer', 'game developer', 'hardware engineer',
       'iot specialist', 'ml engineer', 'mobile app developer',
       'network engineer', 'nlp engineer', 'product manager',
       'qa engineer', 'research scientist', 'robotics engineer',
       'site reliability engineer', 'software engineer',
       'solutions architect', 'speech recognition specialist',
       'system architect', 'technical writer', 'ui/ux designer',
       'virtual reality developer', 'web developer'], dtype=objec

In [57]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [60]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train_trf, y_train_trf)

RandomForestClassifier()

In [64]:
y_pred = rf_model.predict(X_test_trf)

In [65]:
accuracy_score(y_pred, y_test_trf)

0.024

In [66]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(RandomForestClassifier(), X_train_trf, y_train_trf, cv=5)
print(scores, scores.mean())

[0.025   0.0275  0.025   0.0375  0.02875] 0.028750000000000005


In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/new_career_dataset.csv')

In [3]:
df.head()

Interest   Skill_Level Work_Style  Education Personality Problem_Solving  \
0         art        expert   flexible    masters     thinker        creative   
1  technology      advanced   flexible        phd     thinker         logical   
2         art  intermediate       team        phd   extrovert       intuitive   
3    business        expert     remote    diploma   extrovert       intuitive   
4  technology        expert       solo  bachelors     thinker        creative   

        Tech Communication     Leadership Creativity  \
0  very high     excellent         strong     medium   
1       high          poor       moderate  very high   
2       high     excellent  collaborative        low   
3       high        fluent  collaborative       high   
4  very high     excellent      visionary     medium   

                          Career  
0               business analyst  
1      site reliability engineer  
2              financial analyst  
3  speech recognition specialist  
4                 game developer

In [15]:
df.Creativity.unique()

array(['medium', 'very high', 'low', 'high', 'exceptional'], dtype=object)