In [6]:
import os

if os.path.exists(r'data\new_career_dataset.csv'):
    print('exist')

exist


In [7]:
from dataclasses import dataclass
import pandas as pd

@dataclass
class DataPath:
    data_path: str = r'data\new_career_dataset.csv'
    artifact_data_path = r'artifacts/data.csv'

paths = DataPath()

df = pd.read_csv(paths.data_path)
df.head()

Interest   Skill_Level Work_Style  Education Personality Problem_Solving  \
0         art        expert   flexible    masters     thinker        creative   
1  technology      advanced   flexible        phd     thinker         logical   
2         art  intermediate       team        phd   extrovert       intuitive   
3    business        expert     remote    diploma   extrovert       intuitive   
4  technology        expert       solo  bachelors     thinker        creative   

        Tech Communication     Leadership Creativity  \
0  very high     excellent         strong     medium   
1       high          poor       moderate  very high   
2       high     excellent  collaborative        low   
3       high        fluent  collaborative       high   
4  very high     excellent      visionary     medium   

                          Career  
0               business analyst  
1      site reliability engineer  
2              financial analyst  
3  speech recognition specialist  
4                 game developer

In [43]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [44]:
X = df.drop(['Career'], axis=1)
y = df['Career']

In [45]:
columns = X.columns

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [47]:
preprocessor = ColumnTransformer([
    ('OHE', OneHotEncoder(sparse_output=False), columns)
], remainder='passthrough')

In [48]:
X_train_trf = preprocessor.fit_transform(X_train)
X_test_trf = preprocessor.transform(X_test)

In [49]:
le = LabelEncoder()

y_train_trf = le.fit_transform(y_train)
y_test_trf = le.transform(y_test)

In [34]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=0.2)

In [35]:
test.shape

(1000, 11)

In [38]:
df

Interest   Skill_Level Work_Style    Education Personality  \
0            art        expert   flexible      masters     thinker   
1     technology      advanced   flexible          phd     thinker   
2            art  intermediate       team          phd   extrovert   
3       business        expert     remote      diploma   extrovert   
4     technology        expert       solo    bachelors     thinker   
...          ...           ...        ...          ...         ...   
4995  technology      advanced       solo    bachelors     thinker   
4996     science  intermediate   flexible  high school   extrovert   
4997         art      advanced   flexible      diploma   introvert   
4998    medicine  intermediate       team      masters        doer   
4999    medicine      advanced   flexible      diploma   extrovert   

     Problem_Solving       Tech Communication     Leadership   Creativity  \
0           creative  very high     excellent         strong       medium   
1            logical       high          poor       moderate    very high   
2          intuitive       high     excellent  collaborative          low   
3          intuitive       high        fluent  collaborative         high   
4           creative  very high     excellent      visionary       medium   
...              ...        ...           ...            ...          ...   
4995       intuitive  very high        fluent  collaborative          low   
4996         logical     medium          poor  collaborative       medium   
4997       intuitive  very high          poor      visionary         high   
4998        creative  very high          poor       moderate         high   
4999      analytical       high   outstanding      visionary  exceptional   

                             Career  
0                  business analyst  
1         site reliability engineer  
2                 financial analyst  
3     speech recognition specialist  
4                    game developer  
...                             ...  
4995                  web developer  
4996            automation engineer  
4997               technical writer  
4998                 iot specialist  
4999       computer vision engineer  

[5000 rows x 11 columns]

In [51]:
X_train_trf, X_test_trf, y_train_trf, y_test_trf

(array([[0., 1., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 1., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 1., 0.]]),
 array([[0., 0., 1., ..., 1., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        ...,
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 1., 0.]]),
 array([10,  4, 25, ..., 31, 30, 26]),
 array([20,  6,  7, 35, 32, 32,  8,  2,  5, 26, 16,  4, 11, 18, 24,  6, 32,
         4, 33, 32,  4, 19, 22, 20, 37,  2, 31,  1, 28,  0, 32, 38, 36,  1,
        19,  3,  8, 18, 25,  5, 19, 31, 29, 34, 25,  3, 28, 17, 29, 34, 32,
        21, 19, 30, 17, 32,  5, 38,  2,  6, 23,  7, 34, 23, 19,  5, 14, 35,
         3, 13,  3,  8, 20, 34, 25,  4, 28, 10, 23, 14, 10, 27,  4, 30, 33,
         2, 12, 19,  8, 14, 10, 32, 28, 38, 38, 17,  7, 14, 33,  0, 39, 26,
       

In [90]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2

In [61]:
len(le.classes_)

40

In [91]:
model = Sequential()
model.add(Dense(256, activation='relu', input_shape=(X_train_trf.shape[1],), kernel_regularizer=l2(0.01)))
# model.add(Dropout(0.2))
model.add(Dense(128, activation='relu', kernel_regularizer=l2(0.01)))
model.add(Dense(64, activation='relu', kernel_regularizer=l2(0.01)))
# model.add(Dropout(0.2))
model.add(Dense(40, activation='softmax'))

In [92]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_23 (Dense)                │ (None, 256)            │        12,288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_26 (Dense)                │ (None, 40)             │         2,600 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 56,040 (218.91 KB)

 Trainable params: 56,040 (218.91 KB)

 Non-trainable params: 0 (0.00 B)

In [93]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [94]:
model.fit(
    X_train_trf, 
    y_train_trf,
    validation_data=(X_test_trf, y_test_trf),
    epochs=20
)

Epoch 1/20


125/125 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0251 - loss: 5.8726 - val_accuracy: 0.0260 - val_loss: 3.9884
Epoch 2/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0267 - loss: 3.8611 - val_accuracy: 0.0300 - val_loss: 3.7053
Epoch 3/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0289 - loss: 3.6972 - val_accuracy: 0.0300 - val_loss: 3.6904
Epoch 4/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0288 - loss: 3.6876 - val_accuracy: 0.0300 - val_loss: 3.6899
Epoch 5/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0363 - loss: 3.6866 - val_accuracy: 0.0300 - val_loss: 3.6904
Epoch 6/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0292 - loss: 3.6868 - val_accuracy: 0.0300 - val_loss: 3.6908
Epoch 7/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0292 - loss: 3.6872 - val_accuracy: 0.0300 - val_loss: 3.6911
Epoch 8/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0299 - loss: 3.6865 - val_accuracy: 0.0230 - val_

In [98]:
X_test

Interest   Skill_Level Work_Style    Education Personality  \
2891    medicine        expert     office      masters        doer   
493     business      advanced       team  high school        doer   
670      science      beginner     office  high school      leader   
3610  technology      advanced     remote          phd     thinker   
4773    medicine      beginner       solo          phd   extrovert   
...          ...           ...        ...          ...         ...   
1129         art      beginner       solo  high school      leader   
2894     science      advanced       solo      diploma   introvert   
138     business  intermediate       solo      diploma      leader   
592     medicine        expert       team    bachelors     thinker   
3517         art      beginner       team    bachelors   introvert   

     Problem_Solving    Tech Communication     Leadership   Creativity  
2891         logical     low          poor  collaborative          low  
493         creative  medium        fluent  collaborative         high  
670         creative  medium          poor       moderate          low  
3610       practical    high   outstanding      visionary  exceptional  
4773         logical     low          poor  collaborative          low  
...              ...     ...           ...            ...          ...  
1129         logical    high   outstanding      visionary    very high  
2894        creative     low          poor  collaborative          low  
138        practical  medium        fluent         strong  exceptional  
592       analytical  medium     excellent  collaborative  exceptional  
3517         logical  medium          poor         strong       medium  

[1000 rows x 10 columns]

In [156]:
input_qurie = list(X_test.loc[2894])

In [157]:
import numpy as np

input_qurie = pd.DataFrame(np.array([input_qurie]), columns=columns)

In [158]:
input_qurie

Interest Skill_Level Work_Style Education Personality Problem_Solving Tech  \
0  science    advanced       solo   diploma   introvert        creative  low   

  Communication     Leadership Creativity  
0          poor  collaborative        low

In [159]:
prediction_input = np.array([preprocessor.transform(input_qurie)[0]])

In [160]:
prediction_input

array([[0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [161]:
prediction = model.predict(prediction_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


In [162]:
prediction

array([[0.02396186, 0.02263361, 0.0234366 , 0.0231523 , 0.02599659,
        0.02623536, 0.02284913, 0.02545882, 0.02301746, 0.02569979,
        0.02785396, 0.02876105, 0.02372194, 0.02597085, 0.02383758,
        0.0267227 , 0.0255262 , 0.02420458, 0.02856317, 0.0243386 ,
        0.02598333, 0.02588741, 0.02683465, 0.02321241, 0.02278556,
        0.02470937, 0.0265565 , 0.02340666, 0.02365896, 0.02555453,
        0.0216676 , 0.02251566, 0.02678259, 0.02429385, 0.0263499 ,
        0.02456799, 0.02657984, 0.0277435 , 0.02301442, 0.02595302]],
      dtype=float32)

In [163]:
np.argmax(prediction, axis=1)[0]

11

In [164]:
le.classes_[np.argmax(prediction, axis=1)[0]]

'data analyst'